"""
Large-Scale Synthetic Training Data Generator for CyberFlow AI/Data Engine.

Generates hundreds of realistic fraud cases with thousands of transactions
to train real ML models (XGBoost/LightGBM). The data encodes genuine 
statistical relationships between transaction patterns and fraud outcomes
so models learn meaningful signals, not noise.

All data is 100% synthetic. No real NCRP/I4C/bank data is used or implied.
"""

import json
import os
import random
import math
from datetime import datetime, timedelta, timezone
from collections import defaultdict
import pandas as pd
import numpy as np
import networkx as nx

from behavioral import assign_device_fingerprints, compute_behavioral_features, BEHAVIORAL_FEATURE_COLS

# ── Contract vocabulary (00_SHARED_CONTRACT.md) ────────────────────────
OPERATION_STATES = ["emerging", "collection", "distribution", "layering", "consolidation", "cashout_prep"]
NEXT_ACTIONS = ["cashout", "further_layering", "external_transfer", "other"]
FRAUD_TYPES = ["investment_scam", "digital_arrest", "fake_payment_gateway"]
ZONES = ["zone_a", "zone_b", "zone_c"]
PRIORITIES = ["HIGH", "MEDIUM", "LOW"]

# "legitimate_business" is NOT a fraud type in the contract vocabulary
# above (it never appears as a demo investigation case) — it is a
# separate label used ONLY to generate legitimate-business test
# scenarios for model evaluation (requirement: false-positive testing).
# See evaluation.py.
LEGITIMATE_LABEL = "legitimate_business"
SCENARIO_TYPES = FRAUD_TYPES + [LEGITIMATE_LABEL]

ZONE_COORDS = {
    "zone_a": {"lat": 28.6139, "lng": 77.2090},
    "zone_b": {"lat": 22.5726, "lng": 88.3639},
    "zone_c": {"lat": 19.0760, "lng": 72.8777},
}

# ── Scenario behaviour profiles ───────────────────────────────────────
# These encode real statistical relationships so models learn actual patterns

SCENARIO_PROFILES = {
    "investment_scam": {
        "victim_count_range": (2, 6),
        "mule_layers": (2, 4),
        "amount_range_per_victim": (50000, 500000),
        "inter_arrival_base_sec": (20, 120),     # rapid burst
        "typical_final_states": ["consolidation", "cashout_prep", "layering"],
        "state_weights": [0.05, 0.15, 0.15, 0.25, 0.30, 0.10],
        "cashout_zone_bias": "zone_b",
        "description": "Multiple victims recruited, funds pooled then layered through mule networks"
    },
    "digital_arrest": {
        "victim_count_range": (1, 2),
        "mule_layers": (1, 3),
        "amount_range_per_victim": (100000, 1000000),
        "inter_arrival_base_sec": (10, 60),      # very rapid
        "typical_final_states": ["layering", "cashout_prep", "consolidation"],
        "state_weights": [0.05, 0.10, 0.10, 0.35, 0.20, 0.20],
        "cashout_zone_bias": "zone_a",
        "description": "Single victim coerced under threat, rapid ATM cashout"
    },
    "fake_payment_gateway": {
        "victim_count_range": (3, 10),
        "mule_layers": (2, 5),
        "amount_range_per_victim": (10000, 300000),
        "inter_arrival_base_sec": (60, 600),     # slower, spread over time
        "typical_final_states": ["distribution", "layering", "consolidation"],
        "state_weights": [0.05, 0.20, 0.30, 0.25, 0.15, 0.05],
        "cashout_zone_bias": "zone_c",
        "description": "Multiple victims pay into fake merchant, funds distributed to shell accounts"
    }
}

# ── Legitimate-business behaviour profile ───────────────────────────────
# Requirement: "legitimate-business test scenarios such as recurring
# small transactions followed by a large supplier payment." This is
# generated by a dedicated method (below), not the mule-layering
# topology above, because the whole point is that it looks structurally
# nothing like a fraud case: one paying account, no hops, no fan-out,
# same device, business hours.
LEGITIMATE_PROFILE = {
    "recurring_txn_range": (6, 14),          # small recurring payments (e.g. payroll/vendor)
    "recurring_amount_range": (2000, 25000),
    "supplier_payment_range": (150000, 900000),  # the one large payment
    "description": "Recurring small vendor/payroll-style payments from one business "
                    "account, followed by a single larger supplier payment. No fraud "
                    "involved — used only to test the model's false-positive rate.",
}


class SyntheticCaseGenerator:
    """
    Generates realistic synthetic fraud cases with proper statistical
    relationships between features and outcomes.
    """

    def __init__(self, seed=42):
        self.rng = random.Random(seed)
        self.np_rng = np.random.RandomState(seed)
        self.account_counter = 1000
        self.txn_counter = 0

    def _next_account(self, prefix="ACC"):
        self.account_counter += 1
        return f"{prefix}-{self.account_counter}"

    def _next_txn_id(self):
        self.txn_counter += 1
        return f"TXN-{self.txn_counter:06d}"

    def generate_single_case(self, case_id, fraud_type, target_state=None):
        """
        Generate a complete case with realistic transaction patterns.
        Returns (transactions_list, ground_truth_dict).
        """
        profile = SCENARIO_PROFILES[fraud_type]

        # Decide how far this case has progressed
        if target_state:
            final_state_idx = OPERATION_STATES.index(target_state)
        else:
            final_state_idx = self.np_rng.choice(
                len(OPERATION_STATES),
                p=np.array(profile["state_weights"]) / sum(profile["state_weights"])
            )
        final_state = OPERATION_STATES[final_state_idx]

        # Determine next action based on state
        # ~15% of layering/distribution cases should predict external_transfer
        # to ensure all 4 action classes are represented in training data
        force_external = self.rng.random() < 0.15 and final_state in ("layering", "distribution")

        if force_external:
            # External transfer scenario: funds moving to crypto/hawala/external services
            next_action_probs = {
                "external_transfer": 0.50 + self.rng.uniform(0, 0.25),
                "cashout": 0.0, "further_layering": 0.0, "other": 0.0
            }
            remainder = 1.0 - next_action_probs["external_transfer"]
            next_action_probs["further_layering"] = remainder * self.rng.uniform(0.3, 0.5)
            next_action_probs["cashout"] = remainder * self.rng.uniform(0.2, 0.4)
            next_action_probs["other"] = max(0.0, 1.0 - sum(next_action_probs.values()))
        elif final_state in ("consolidation", "cashout_prep"):
            next_action_probs = {"cashout": 0.65 + self.rng.uniform(0, 0.25),
                                 "further_layering": 0.0, "external_transfer": 0.0, "other": 0.0}
            remainder = 1.0 - next_action_probs["cashout"]
            next_action_probs["further_layering"] = remainder * self.rng.uniform(0.3, 0.6)
            next_action_probs["external_transfer"] = remainder * self.rng.uniform(0.1, 0.3)
            next_action_probs["other"] = max(0.0, 1.0 - sum(next_action_probs.values()))
        elif final_state in ("layering", "distribution"):
            next_action_probs = {"further_layering": 0.40 + self.rng.uniform(0, 0.30),
                                 "cashout": 0.0, "external_transfer": 0.0, "other": 0.0}
            remainder = 1.0 - next_action_probs["further_layering"]
            next_action_probs["cashout"] = remainder * self.rng.uniform(0.3, 0.6)
            next_action_probs["external_transfer"] = remainder * self.rng.uniform(0.2, 0.5)
            next_action_probs["other"] = max(0.0, 1.0 - sum(next_action_probs.values()))
        else:
            next_action_probs = {"other": 0.40 + self.rng.uniform(0, 0.20),
                                 "cashout": 0.0, "further_layering": 0.0, "external_transfer": 0.0}
            remainder = 1.0 - next_action_probs["other"]
            next_action_probs["further_layering"] = remainder * self.rng.uniform(0.3, 0.5)
            next_action_probs["cashout"] = remainder * self.rng.uniform(0.1, 0.3)
            next_action_probs["external_transfer"] = max(0.0, 1.0 - sum(next_action_probs.values()))

        # Normalize probabilities
        total_p = sum(next_action_probs.values())
        next_action_probs = {k: round(v / total_p, 4) for k, v in next_action_probs.items()}
        predicted_action = max(next_action_probs, key=next_action_probs.get)

        # Risk score — correlated with state progression and fraud type velocity
        base_risk = (final_state_idx / 5.0) * 0.6 + 0.2
        noise = self.rng.uniform(-0.08, 0.12)
        if fraud_type == "digital_arrest":
            noise += 0.10  # digital arrest is inherently higher risk due to speed
        network_risk = round(min(0.99, max(0.05, base_risk + noise)), 2)

        # Priority
        if network_risk >= 0.75:
            priority = "HIGH"
        elif network_risk >= 0.50:
            priority = "MEDIUM"
        else:
            priority = "LOW"

        # Generate transaction topology
        num_victims = self.rng.randint(*profile["victim_count_range"])
        num_mule_layers = self.rng.randint(*profile["mule_layers"])
        
        # Clamp layers based on how far case progressed
        active_layers = min(num_mule_layers, max(1, final_state_idx))

        victim_accounts = [self._next_account("VICTIM") for _ in range(num_victims)]
        
        # Amount per victim
        amounts = [self.rng.uniform(*profile["amount_range_per_victim"]) for _ in range(num_victims)]
        total_exposure = sum(amounts)

        # Primary collection node
        collection_acc = self._next_account("COLL")
        
        # Cashout zone selection
        primary_zone = profile["cashout_zone_bias"]
        zones_used = [primary_zone]
        if self.rng.random() > 0.4:
            secondary = self.rng.choice([z for z in ZONES if z != primary_zone])
            zones_used.append(secondary)

        # Build transaction list following the state progression
        base_time = datetime(2026, 8, 22, self.rng.randint(8, 22), 
                            self.rng.randint(0, 59), 0, tzinfo=timezone.utc)
        transactions = []
        current_time = base_time

        # ── Phase 1: Collection (victims → collection node) ──
        if final_state_idx >= 1:  # at least collection
            for i, (v_acc, amt) in enumerate(zip(victim_accounts, amounts)):
                delay = self.rng.randint(0, 300)
                current_time = current_time + timedelta(seconds=delay)
                transactions.append(self._make_tx(
                    case_id, fraud_type, v_acc, collection_acc,
                    round(amt, 2), current_time,
                    self.rng.choice(zones_used), "collection"
                ))

        # ── Phase 2: Distribution (collection → primary mules) ──
        primary_mules = []
        if final_state_idx >= 2:
            n_primary = self.rng.randint(2, min(5, num_victims + 1))
            primary_mules = [self._next_account("MULE1") for _ in range(n_primary)]
            split_amounts = self._split_amount(total_exposure, n_primary)
            
            burst_gap = self.rng.randint(*profile["inter_arrival_base_sec"])
            for m_acc, m_amt in zip(primary_mules, split_amounts):
                current_time = current_time + timedelta(seconds=burst_gap)
                transactions.append(self._make_tx(
                    case_id, fraud_type, collection_acc, m_acc,
                    round(m_amt, 2), current_time,
                    self.rng.choice(zones_used), "distribution"
                ))

        # ── Phase 3: Layering (primary mules → secondary mules) ──
        secondary_mules = []
        if final_state_idx >= 3 and primary_mules:
            for pm in primary_mules:
                n_sec = self.rng.randint(1, 3)
                pm_amount = sum(t["amount"] for t in transactions 
                               if t["destination_account"] == pm)
                sec_splits = self._split_amount(pm_amount, n_sec)
                for s_amt in sec_splits:
                    sec_acc = self._next_account("MULE2")
                    secondary_mules.append(sec_acc)
                    burst_gap = self.rng.randint(*profile["inter_arrival_base_sec"])
                    current_time = current_time + timedelta(seconds=burst_gap)
                    transactions.append(self._make_tx(
                        case_id, fraud_type, pm, sec_acc,
                        round(s_amt, 2), current_time,
                        primary_zone, "layering"
                    ))

        # ── Phase 4: Consolidation (secondary → consolidation hubs) ──
        if final_state_idx >= 4 and secondary_mules:
            n_hubs = self.rng.randint(1, 3)
            hubs = [self._next_account("HUB") for _ in range(n_hubs)]
            for sm in secondary_mules:
                sm_amount = sum(t["amount"] for t in transactions 
                               if t["destination_account"] == sm)
                if sm_amount > 0:
                    hub = self.rng.choice(hubs)
                    burst_gap = self.rng.randint(*profile["inter_arrival_base_sec"])
                    current_time = current_time + timedelta(seconds=burst_gap)
                    transactions.append(self._make_tx(
                        case_id, fraud_type, sm, hub,
                        round(sm_amount, 2), current_time,
                        primary_zone, "consolidation"
                    ))

        # ── Phase 5: Cashout prep (hubs → ATM/withdrawal accounts) ──
        if final_state_idx >= 5:
            active_hubs = list(set(t["destination_account"] for t in transactions 
                                   if t["operation_state"] == "consolidation"))
            if not active_hubs:
                active_hubs = [transactions[-1]["destination_account"]] if transactions else []
            for hub in active_hubs:
                hub_amt = sum(t["amount"] for t in transactions 
                             if t["destination_account"] == hub)
                if hub_amt > 0:
                    cashout_acc = self._next_account("CASHOUT")
                    current_time = current_time + timedelta(seconds=self.rng.randint(30, 120))
                    transactions.append(self._make_tx(
                        case_id, fraud_type, hub, cashout_acc,
                        round(hub_amt, 2), current_time,
                        primary_zone, "cashout_prep"
                    ))

        # If case is emerging (state 0), generate just a few initial transfers
        if final_state_idx == 0:
            for i, (v_acc, amt) in enumerate(zip(victim_accounts[:2], amounts[:2])):
                delay = self.rng.randint(60, 600)
                current_time = current_time + timedelta(seconds=delay)
                transactions.append(self._make_tx(
                    case_id, fraud_type, v_acc, collection_acc,
                    round(amt * self.rng.uniform(0.1, 0.4), 2), current_time,
                    self.rng.choice(zones_used), "emerging"
                ))

        # Location candidates
        zone_confs = {}
        for z in ZONES:
            if z == primary_zone:
                zone_confs[z] = round(0.50 + self.rng.uniform(0.1, 0.40), 2)
            else:
                zone_confs[z] = round(self.rng.uniform(0.10, 0.55), 2)

        ground_truth = {
            "case_id": case_id,
            "fraud_type": fraud_type,
            "is_fraud": 1,
            "current_state": final_state,
            "network_risk": network_risk,
            "predicted_next_action": predicted_action,
            "next_action_probs": next_action_probs,
            "potential_exposure_inr": round(total_exposure, 0),
            "intervention_priority": priority,
            "primary_zone": primary_zone,
            "zone_confidences": zone_confs,
            "num_victims": num_victims,
            "num_mule_layers": active_layers,
            "transaction_count": len(transactions),
            "time_span_sec": (current_time - base_time).total_seconds() if transactions else 0,
        }

        return transactions, ground_truth

    def _make_tx(self, case_id, fraud_type, src, dst, amount, timestamp, zone, state):
        coords = ZONE_COORDS[zone]
        # Add small coordinate jitter for realism
        lat = coords["lat"] + self.rng.uniform(-0.05, 0.05)
        lng = coords["lng"] + self.rng.uniform(-0.05, 0.05)
        return {
            "transaction_id": self._next_txn_id(),
            "timestamp": timestamp.isoformat().replace("+00:00", "Z"),
            "source_account": src,
            "destination_account": dst,
            "amount": amount,
            "transaction_type": "transfer",
            "location_id": zone,
            "latitude": round(lat, 4),
            "longitude": round(lng, 4),
            "case_id": case_id,
            "fraud_type": fraud_type,
            "operation_state": state,
        }

    def _split_amount(self, total, n):
        """Split total into n parts with realistic variance."""
        if n <= 0:
            return []
        weights = [self.rng.uniform(0.5, 1.5) for _ in range(n)]
        s = sum(weights)
        return [total * w / s for w in weights]

    def generate_legitimate_case(self, case_id):
        """
        Generate a legitimate-business case: recurring small payments from
        ONE business account to a handful of regular counterparties
        (vendors/payroll-style), all within business hours, from a
        consistent device, followed by a single larger supplier payment.

        No mule layering, no convergence, no multi-zone burst — this is
        deliberately the "large transaction alone" scenario the model
        must NOT flag as high risk on amount alone. Ground truth is
        LOW risk / not fraud.
        """
        profile = LEGITIMATE_PROFILE
        business_acc = self._next_account("BIZ")
        n_recurring = self.rng.randint(*profile["recurring_txn_range"])
        counterparties = [self._next_account("VEND") for _ in range(max(2, n_recurring // 3))]
        zone = self.rng.choice(ZONES)

        # Spread recurring payments across ~20 business days, business hours only.
        base_day = datetime(2026, 8, 1, tzinfo=timezone.utc)
        transactions = []
        total_recurring = 0.0
        for i in range(n_recurring):
            day_offset = self.rng.randint(0, 20)
            hour = self.rng.randint(9, 17)
            minute = self.rng.randint(0, 59)
            ts = base_day + timedelta(days=day_offset, hours=hour, minutes=minute)
            amt = round(self.rng.uniform(*profile["recurring_amount_range"]), 2)
            total_recurring += amt
            counterparty = self.rng.choice(counterparties)
            transactions.append(self._make_tx(
                case_id, LEGITIMATE_LABEL, business_acc, counterparty,
                amt, ts, zone, "emerging"
            ))

        # One larger supplier payment near the end of the window, still
        # within business hours, from the SAME account.
        supplier_acc = self._next_account("SUPPLIER")
        supplier_amt = round(self.rng.uniform(*profile["supplier_payment_range"]), 2)
        ts = base_day + timedelta(days=self.rng.randint(21, 25), hours=self.rng.randint(9, 17))
        transactions.append(self._make_tx(
            case_id, LEGITIMATE_LABEL, business_acc, supplier_acc,
            supplier_amt, ts, zone, "emerging"
        ))
        transactions.sort(key=lambda t: t["timestamp"])

        total_exposure = total_recurring + supplier_amt
        ground_truth = {
            "case_id": case_id,
            "fraud_type": LEGITIMATE_LABEL,
            "is_fraud": 0,
            "current_state": "emerging",
            "network_risk": round(self.rng.uniform(0.05, 0.18), 2),
            "predicted_next_action": "other",
            "next_action_probs": {"other": 0.7, "further_layering": 0.1,
                                   "cashout": 0.1, "external_transfer": 0.1},
            "potential_exposure_inr": round(total_exposure, 0),
            "intervention_priority": "LOW",
            "primary_zone": zone,
            "zone_confidences": {z: (0.6 if z == zone else 0.2) for z in ZONES},
            "num_victims": 0,
            "num_mule_layers": 0,
            "transaction_count": len(transactions),
            "time_span_sec": 0,
        }
        return transactions, ground_truth


def compute_case_features(case_id, transactions, fraud_type):
    """
    Compute the full feature vector for a single case from its transactions.
    This is the SAME feature engineering used at training AND inference time.
    """
    case_txs = [t for t in transactions if t["case_id"] == case_id]
    if not case_txs:
        return None

    df = pd.DataFrame(case_txs)
    df["dt"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values("dt")

    # ── Transaction features ──
    total_volume = float(df["amount"].sum())
    tx_count = len(df)
    max_amount = float(df["amount"].max())
    min_amount = float(df["amount"].min())
    mean_amount = float(df["amount"].mean())
    std_amount = float(df["amount"].std()) if tx_count > 1 else 0.0

    time_span_sec = max((df["dt"].max() - df["dt"].min()).total_seconds(), 1.0)
    velocity = tx_count / (time_span_sec / 60.0)

    # Inter-arrival times
    if tx_count > 1:
        diffs = df["dt"].diff().dt.total_seconds().dropna()
        min_iat = float(diffs.min())
        mean_iat = float(diffs.mean())
        std_iat = float(diffs.std()) if len(diffs) > 1 else 0.0
        rapid_count = int((diffs <= 60).sum())
        burst_ratio = rapid_count / max(tx_count - 1, 1)
    else:
        min_iat = 0.0
        mean_iat = 0.0
        std_iat = 0.0
        rapid_count = 0
        burst_ratio = 0.0

    # ── Network / graph features ──
    G = nx.DiGraph()
    for _, row in df.iterrows():
        G.add_edge(row["source_account"], row["destination_account"], amount=row["amount"])

    num_nodes = G.number_of_nodes()
    num_edges = G.number_of_edges()
    
    in_degs = [d for _, d in G.in_degree()]
    out_degs = [d for _, d in G.out_degree()]
    max_fan_in = max(in_degs) if in_degs else 0
    max_fan_out = max(out_degs) if out_degs else 0
    mean_fan_in = float(np.mean(in_degs)) if in_degs else 0.0
    mean_fan_out = float(np.mean(out_degs)) if out_degs else 0.0

    # Source-only nodes (victims) vs sink-only nodes
    sources_only = sum(1 for n in G.nodes() if G.in_degree(n) == 0 and G.out_degree(n) > 0)
    sinks_only = sum(1 for n in G.nodes() if G.out_degree(n) == 0 and G.in_degree(n) > 0)

    # Convergence: nodes with fan-in >= 3
    convergence_nodes = sum(1 for _, d in G.in_degree() if d >= 3)
    convergence_ratio = convergence_nodes / max(num_nodes, 1)

    # Centrality
    try:
        betweenness = nx.betweenness_centrality(G)
        max_betweenness = float(max(betweenness.values())) if betweenness else 0.0
        mean_betweenness = float(np.mean(list(betweenness.values()))) if betweenness else 0.0
    except Exception:
        max_betweenness = 0.0
        mean_betweenness = 0.0

    # Longest path (hop depth) — use DAG longest path if possible
    try:
        if nx.is_directed_acyclic_graph(G):
            hop_depth = nx.dag_longest_path_length(G)
        else:
            hop_depth = num_edges  # fallback
    except Exception:
        hop_depth = 0

    # ── Spatial features ──
    zone_counts = df["location_id"].value_counts()
    zone_a_frac = float(zone_counts.get("zone_a", 0)) / max(tx_count, 1)
    zone_b_frac = float(zone_counts.get("zone_b", 0)) / max(tx_count, 1)
    zone_c_frac = float(zone_counts.get("zone_c", 0)) / max(tx_count, 1)
    num_zones_active = int((zone_counts > 0).sum())

    # ── Fraud type encoding ──
    ft_investment = 1 if fraud_type == "investment_scam" else 0
    ft_digital = 1 if fraud_type == "digital_arrest" else 0
    ft_gateway = 1 if fraud_type == "fake_payment_gateway" else 0
    ft_legit = 1 if fraud_type == LEGITIMATE_LABEL else 0

    # ── Contextual / behavioural features (requirement 5) ──
    # Same function at training and inference time — see behavioral.py.
    behavioral_feats = compute_behavioral_features(df)

    return {
        "case_id": case_id,
        # Transaction features
        "total_volume": total_volume,
        "tx_count": tx_count,
        "max_amount": max_amount,
        "min_amount": min_amount,
        "mean_amount": mean_amount,
        "std_amount": std_amount,
        "velocity_tx_per_min": velocity,
        "time_span_sec": time_span_sec,
        "min_inter_arrival_sec": min_iat,
        "mean_inter_arrival_sec": mean_iat,
        "std_inter_arrival_sec": std_iat,
        "rapid_tx_count": rapid_count,
        "burst_ratio": burst_ratio,
        # Network features
        "num_nodes": num_nodes,
        "num_edges": num_edges,
        "max_fan_in": max_fan_in,
        "max_fan_out": max_fan_out,
        "mean_fan_in": mean_fan_in,
        "mean_fan_out": mean_fan_out,
        "sources_only_count": sources_only,
        "sinks_only_count": sinks_only,
        "convergence_ratio": convergence_ratio,
        "max_betweenness": max_betweenness,
        "mean_betweenness": mean_betweenness,
        "hop_depth": hop_depth,
        # Spatial features
        "zone_a_frac": zone_a_frac,
        "zone_b_frac": zone_b_frac,
        "zone_c_frac": zone_c_frac,
        "num_zones_active": num_zones_active,
        # Fraud type (one-hot)
        "ft_investment_scam": ft_investment,
        "ft_digital_arrest": ft_digital,
        "ft_fake_payment_gateway": ft_gateway,
        "ft_legitimate_business": ft_legit,
        # Contextual / behavioural features (requirement 5)
        **behavioral_feats,
    }


# ── Feature column names (must match training & inference) ──
FEATURE_COLS = [
    "total_volume", "tx_count", "max_amount", "min_amount", "mean_amount",
    "std_amount", "velocity_tx_per_min", "time_span_sec",
    "min_inter_arrival_sec", "mean_inter_arrival_sec", "std_inter_arrival_sec",
    "rapid_tx_count", "burst_ratio",
    "num_nodes", "num_edges", "max_fan_in", "max_fan_out",
    "mean_fan_in", "mean_fan_out", "sources_only_count", "sinks_only_count",
    "convergence_ratio", "max_betweenness", "mean_betweenness", "hop_depth",
    "zone_a_frac", "zone_b_frac", "zone_c_frac", "num_zones_active",
    "ft_investment_scam", "ft_digital_arrest", "ft_fake_payment_gateway", "ft_legitimate_business",
] + BEHAVIORAL_FEATURE_COLS


def derive_labels_from_features(feats, fraud_type, rng):
    """
    Derive risk, next-action, and priority labels deterministically from
    extracted features. This creates a LEARNABLE mapping so the model
    can achieve high accuracy.

    The rules here encode domain knowledge about cyber-financial crime:
    - Higher hop depth + convergence + velocity → higher risk
    - State + velocity pattern → next action prediction
    - Risk thresholds → priority
    """
    hop = feats.get("hop_depth", 0)
    convergence = feats.get("convergence_ratio", 0)
    velocity = feats.get("velocity_tx_per_min", 0)
    burst_ratio = feats.get("burst_ratio", 0)
    fan_in = feats.get("max_fan_in", 0)
    fan_out = feats.get("max_fan_out", 0)
    num_nodes = feats.get("num_nodes", 1)
    num_edges = feats.get("num_edges", 0)
    total_volume = feats.get("total_volume", 0)
    tx_count = feats.get("tx_count", 1)
    sinks = feats.get("sinks_only_count", 0)
    max_betweenness = feats.get("max_betweenness", 0)
    zone_count = feats.get("num_zones_active", 1)

    # Behavioural / contextual signals (requirement 5) — these exist
    # specifically so a large-but-isolated payment does not, on its own,
    # push risk up the way raw volume alone would.
    tx_count = feats.get("tx_count", 1)
    device_consistency = feats.get("device_consistency_ratio", 0.5)
    recurring_ratio = feats.get("recurring_amount_ratio", 0.5)
    account_reuse = feats.get("account_reuse_ratio", 1.0)

    # ── Normalized components, each in [0, 1] ──
    hop_component = min(hop / 4.0, 1.0)                    # deeper = riskier
    velocity_component = min(velocity / 3.0, 1.0)          # faster = riskier
    convergence_component = min(convergence * 4.0, 1.0)    # convergent = riskier
    burst_component = min(burst_ratio * 1.2, 1.0)          # bursty = riskier
    size_component = min(num_edges / 10.0, 1.0)            # larger network = riskier
    fanout_component = min(fan_out / 4.0, 1.0)             # high fanout = riskier
    fanin_component = min(fan_in / 4.0, 1.0)               # high fanin = riskier
    volume_component = min(total_volume / 1000000.0, 1.0)  # higher volume = riskier (small weight — see below)

    # Device churn: 1 - consistency. Only trusted once there's enough
    # transaction history to establish a pattern (tx_count >= 3);
    # otherwise it stays neutral so a single transaction isn't penalized.
    churn_component = (1.0 - device_consistency) if tx_count >= 3 else 0.0
    # Lack of a recurring/regular payment pattern → riskier; a case with
    # too little history (tx_count < 3) gets a mild, neutral value rather
    # than being flagged purely for being small.
    low_recurrence_component = max(0.0, 1.0 - min(recurring_ratio * 1.3, 1.0)) if tx_count >= 3 else 0.35
    # Low account reuse (many one-shot source accounts, e.g. many
    # single-use mule/victim accounts) is a mild risk signal on its own.
    low_reuse_component = max(0.0, 1.0 - min((account_reuse - 1.0) / 3.0, 1.0))

    # ── Network Risk Score ──
    # Weighted combination, then scale to use full [0.05, 0.99] range.
    # Note: volume_component's weight is intentionally small (0.05) —
    # a single large transaction must not dominate the score; topology
    # (hops/convergence/fan-out) and behavioural context (device churn,
    # recurrence) carry far more weight than the raw amount does.
    risk_raw = (
        0.16 * hop_component +
        0.10 * velocity_component +
        0.10 * convergence_component +
        0.09 * burst_component +
        0.09 * size_component +
        0.07 * fanout_component +
        0.06 * fanin_component +
        0.05 * volume_component +
        0.10 * churn_component +
        0.10 * low_recurrence_component +
        0.04 * low_reuse_component +
        0.04 * min(zone_count / 3.0, 1.0)
    )
    # weights sum to 1.00

    # Scale to use wider range
    risk_scaled = 0.05 + risk_raw * 1.20
    network_risk = round(min(0.99, max(0.05, risk_scaled)), 2)

    # ── Priority (thresholds tuned for balanced distribution) ──
    if network_risk >= 0.80:
        priority = "HIGH"
    elif network_risk >= 0.50:
        priority = "MEDIUM"
    else:
        priority = "LOW"

    # ── Next Action (feature-driven scoring) ──
    # cashout: high convergence + deep hops + high burst → funds are consolidating for withdrawal
    cashout_score = (hop_component * 0.30 + convergence_component * 0.25 +
                     burst_component * 0.20 + fanin_component * 0.15 +
                     velocity_component * 0.10)

    # further_layering: high fanout + large network + low convergence → still dispersing
    layering_score = (fanout_component * 0.30 + size_component * 0.25 +
                      (1.0 - convergence_component) * 0.20 + velocity_component * 0.15 +
                      volume_component * 0.10)

    # external_transfer: multi-zone + high betweenness + low burst → cross-border/service transfer
    external_score = (min(zone_count / 2.5, 1.0) * 0.30 +
                      min(max_betweenness * 3.0, 1.0) * 0.25 +
                      (1.0 - burst_component) * 0.20 +
                      velocity_component * 0.15 +
                      volume_component * 0.10)

    # other: low activity across the board → case is early-stage or unclear
    activity_level = (hop_component + velocity_component + size_component + burst_component) / 4.0
    other_score = max(0.0, 0.60 - activity_level * 0.70)

    scores = {
        "cashout": cashout_score,
        "further_layering": layering_score,
        "external_transfer": external_score,
        "other": other_score
    }
    predicted_action = max(scores, key=scores.get)

    return {
        "network_risk": network_risk,
        "intervention_priority": priority,
        "predicted_next_action": predicted_action,
    }


def generate_training_dataset(num_cases=1000, seed=42, output_dir="data", legit_fraction=0.15):
    """
    Generate a large-scale training dataset with feature-derived labels.

    Flow:
    1. Generate transaction topology per case (fraud cases + a share of
       legitimate-business cases, so the model sees both — requirement 6)
    2. Assign synthetic device fingerprints (requirement 5)
    3. Extract features from transactions + graph
    4. Derive labels FROM features (so the model learns a real function)
    """
    os.makedirs(output_dir, exist_ok=True)

    gen = SyntheticCaseGenerator(seed=seed)
    rng = random.Random(seed + 999)
    all_transactions = []
    all_ground_truths = []
    case_counter = 0

    num_legit = int(round(num_cases * legit_fraction))
    num_fraud = num_cases - num_legit

    # Distribute fraud cases across fraud types
    cases_per_type = num_fraud // 3
    remainder = num_fraud % 3

    print(f"[+] Generating {num_fraud} fraud cases + {num_legit} legitimate-business cases...")
    for ft_idx, fraud_type in enumerate(FRAUD_TYPES):
        n = cases_per_type + (1 if ft_idx < remainder else 0)
        for i in range(n):
            case_counter += 1
            case_id = f"TRAIN-{case_counter:04d}"
            txs, gt = gen.generate_single_case(case_id, fraud_type)
            all_transactions.extend(txs)
            all_ground_truths.append(gt)

    for i in range(num_legit):
        case_counter += 1
        case_id = f"TRAIN-{case_counter:04d}"
        txs, gt = gen.generate_legitimate_case(case_id)
        all_transactions.extend(txs)
        all_ground_truths.append(gt)

    # Synthetic device fingerprints — same function used at inference time
    # (see behavioral.py). Must run before feature extraction.
    assign_device_fingerprints(all_transactions)

    # Compute features and derive labels FROM features
    print(f"[+] Generated {len(all_transactions)} transactions across {len(all_ground_truths)} cases")
    print("[+] Computing features and deriving labels...")

    feature_rows = []
    for gt in all_ground_truths:
        cid = gt["case_id"]
        ft = gt["fraud_type"]
        feats = compute_case_features(cid, all_transactions, ft)
        if feats:
            # Derive labels from features (not random) — same function
            # for fraud AND legitimate cases, so "low risk" for the
            # legitimate cases is something the formula actually
            # produces from their features, not something hand-set.
            derived = derive_labels_from_features(feats, ft, rng)

            row = dict(feats)
            row["current_state"] = gt["current_state"]  # state comes from topology (already good)
            row["network_risk"] = derived["network_risk"]
            row["predicted_next_action"] = derived["predicted_next_action"]
            row["intervention_priority"] = derived["intervention_priority"]
            row["potential_exposure_inr"] = gt["potential_exposure_inr"]
            row["fraud_type"] = gt["fraud_type"]
            row["is_fraud"] = gt.get("is_fraud", 1)
            feature_rows.append(row)

    # Save outputs
    tx_df = pd.DataFrame(all_transactions)
    tx_path = os.path.join(output_dir, "training_transactions.csv")
    tx_df.to_csv(tx_path, index=False)

    feat_df = pd.DataFrame(feature_rows)
    feat_path = os.path.join(output_dir, "training_features.csv")
    feat_df.to_csv(feat_path, index=False)

    gt_path = os.path.join(output_dir, "training_labels.json")
    with open(gt_path, "w") as f:
        json.dump(all_ground_truths, f, indent=2)

    print(f"[+] Saved {len(tx_df)} transactions to: {tx_path}")
    print(f"[+] Saved {len(feat_df)} feature rows to:  {feat_path}")
    print(f"[+] Saved ground truths to: {gt_path}")

    # Print distribution summary
    print("\n=== Dataset Distribution ===")
    print(f"Total cases:  {len(feat_df)}")
    print(f"Fraud types:  {feat_df['fraud_type'].value_counts().to_dict()}")
    print(f"Is-fraud:     {feat_df['is_fraud'].value_counts().to_dict()}")
    print(f"States:       {feat_df['current_state'].value_counts().to_dict()}")
    print(f"Priorities:   {feat_df['intervention_priority'].value_counts().to_dict()}")
    print(f"Next actions: {feat_df['predicted_next_action'].value_counts().to_dict()}")
    print(f"Risk range:   [{feat_df['network_risk'].min():.2f}, {feat_df['network_risk'].max():.2f}]")

    return tx_path, feat_path


if __name__ == "__main__":
    generate_training_dataset(num_cases=1000, seed=42)

